#pragma once
#include <sstream>
#include <vulkan/vulkan.h>



namespace emberVulkanUtility
{
	inline std::string ToString(VkDescriptorType vkDescriptorType)
	{
		std::ostringstream ss;
		switch (vkDescriptorType)
		{
			case VK_DESCRIPTOR_TYPE_SAMPLER:					ss << "VK_DESCRIPTOR_TYPE_SAMPLER"; break;
			case VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER:		ss << "VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER"; break;
			case VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE:				ss << "VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE"; break;
			case VK_DESCRIPTOR_TYPE_STORAGE_IMAGE:				ss << "VK_DESCRIPTOR_TYPE_STORAGE_IMAGE"; break;
			case VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER:		ss << "VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER"; break;
			case VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER:		ss << "VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER"; break;
			case VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER:				ss << "VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER"; break;
			case VK_DESCRIPTOR_TYPE_STORAGE_BUFFER:				ss << "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER"; break;
			case VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC:		ss << "VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC"; break;
			case VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC:		ss << "VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC"; break;
			case VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT:			ss << "VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT"; break;
			case VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK:		ss << "VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK(_EXT)"; break;
			case VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR:	ss << "VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR"; break;
			case VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV:	ss << "VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV"; break;
			case VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM:	ss << "VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM"; break;
			case VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM:		ss << "VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM"; break;
			case VK_DESCRIPTOR_TYPE_MUTABLE_EXT:				ss << "VK_DESCRIPTOR_TYPE_MUTABLE_(EXT/VALVE)"; break;
			case VK_DESCRIPTOR_TYPE_MAX_ENUM:					ss << "VK_DESCRIPTOR_TYPE_MAX_ENUM"; break;
			default: ss << "unknown";
		}
		return ss.str();
	}
}