#include "vulkanPipelineStageFlags2ToString.h"
#include <sstream>



namespace emberVulkanUtility
{
	std::string ToString_VkPipelineStageFlags2(VkPipelineStageFlags2 vkPipelineStageFlags2)
	{
		if (vkPipelineStageFlags2 == 0)
			return "none";

		std::ostringstream ss;
		bool first = true;
		VkPipelineStageFlags2 knownFlags = 0;
		auto append = [&](VkPipelineStageFlagBits2 bit, const char* name)
		{
			knownFlags |= bit;
			if (vkPipelineStageFlags2 & bit)
			{
				if (!first)
					ss << " | ";
				first = false;
				ss << name;
			}
		};

		append(VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT, "VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT");
		append(VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT, "VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT");
		append(VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT, "VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT");
		append(VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT, "VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT, "VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT, "VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT, "VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, "VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT, "VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT");
		append(VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT, "VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT");
		append(VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, "VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT");
		append(VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT, "VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT");
		append(VK_PIPELINE_STAGE_2_TRANSFER_BIT, "VK_PIPELINE_STAGE_2_TRANSFER_BIT");
		append(VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, "VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT");
		append(VK_PIPELINE_STAGE_2_HOST_BIT, "VK_PIPELINE_STAGE_2_HOST_BIT");
		append(VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT, "VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT");
		append(VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, "VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT");
		append(VK_PIPELINE_STAGE_2_COPY_BIT, "VK_PIPELINE_STAGE_2_COPY_BIT");
		append(VK_PIPELINE_STAGE_2_RESOLVE_BIT, "VK_PIPELINE_STAGE_2_RESOLVE_BIT");
		append(VK_PIPELINE_STAGE_2_BLIT_BIT, "VK_PIPELINE_STAGE_2_BLIT_BIT");
		append(VK_PIPELINE_STAGE_2_CLEAR_BIT, "VK_PIPELINE_STAGE_2_CLEAR_BIT");
		append(VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT, "VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT");
		append(VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT, "VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT");
		append(VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT, "VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT");
		append(VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR, "VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR, "VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT, "VK_PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT, "VK_PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_EXT, "VK_PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR, "VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, "VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR, "VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT, "VK_PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT, "VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT, "VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEI, "VK_PIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEI");
		append(VK_PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI, "VK_PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI");
		append(VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR, "VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT, "VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT");
		append(VK_PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI, "VK_PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI");
		append(VK_PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV, "VK_PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV");
		append(VK_PIPELINE_STAGE_2_CONVERT_COOPERATIVE_VECTOR_MATRIX_BIT_NV, "VK_PIPELINE_STAGE_2_CONVERT_COOPERATIVE_VECTOR_MATRIX_BIT_NV");
		append(VK_PIPELINE_STAGE_2_DATA_GRAPH_BIT_ARM, "VK_PIPELINE_STAGE_2_DATA_GRAPH_BIT_ARM");
		append(VK_PIPELINE_STAGE_2_COPY_INDIRECT_BIT_KHR, "VK_PIPELINE_STAGE_2_COPY_INDIRECT_BIT_KHR");
		append(VK_PIPELINE_STAGE_2_MEMORY_DECOMPRESSION_BIT_EXT, "VK_PIPELINE_STAGE_2_MEMORY_DECOMPRESSION_BIT_EXT");

		VkPipelineStageFlags2 unknownFlags = vkPipelineStageFlags2 & ~knownFlags;
		if (unknownFlags != 0)
		{
			if (!first)
				ss << " | ";
			ss << "UNKNOWN_PIPELINE_STAGE_2_BITS(0x" << std::hex << static_cast<uint64_t>(unknownFlags) << std::dec << ")";
		}

		return ss.str();
	}
}