#include "vulkanAccessFlags2ToString.h"
#include <sstream>



namespace emberVulkanUtility
{
	std::string ToString_VkAccessFlags2(VkAccessFlags2 vkAccessFlags2)
	{
		if (vkAccessFlags2 == 0)
			return "none";

		std::ostringstream ss;
		bool first = true;
		VkAccessFlags2 knownFlags = 0;
		auto append = [&](VkAccessFlagBits2 bit, const char* name)
		{
			knownFlags |= bit;
			if (vkAccessFlags2 & bit)
			{
				if (!first)
					ss << " | ";
				first = false;
				ss << name;
			}
		};

		append(VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT, "VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT");
		append(VK_ACCESS_2_INDEX_READ_BIT, "VK_ACCESS_2_INDEX_READ_BIT");
		append(VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT, "VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT");
		append(VK_ACCESS_2_UNIFORM_READ_BIT, "VK_ACCESS_2_UNIFORM_READ_BIT");
		append(VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT, "VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT");
		append(VK_ACCESS_2_SHADER_READ_BIT, "VK_ACCESS_2_SHADER_READ_BIT");
		append(VK_ACCESS_2_SHADER_WRITE_BIT, "VK_ACCESS_2_SHADER_WRITE_BIT");
		append(VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT, "VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT");
		append(VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT, "VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT");
		append(VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT, "VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT");
		append(VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT, "VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT");
		append(VK_ACCESS_2_TRANSFER_READ_BIT, "VK_ACCESS_2_TRANSFER_READ_BIT");
		append(VK_ACCESS_2_TRANSFER_WRITE_BIT, "VK_ACCESS_2_TRANSFER_WRITE_BIT");
		append(VK_ACCESS_2_HOST_READ_BIT, "VK_ACCESS_2_HOST_READ_BIT");
		append(VK_ACCESS_2_HOST_WRITE_BIT, "VK_ACCESS_2_HOST_WRITE_BIT");
		append(VK_ACCESS_2_MEMORY_READ_BIT, "VK_ACCESS_2_MEMORY_READ_BIT");
		append(VK_ACCESS_2_MEMORY_WRITE_BIT, "VK_ACCESS_2_MEMORY_WRITE_BIT");
		append(VK_ACCESS_2_SHADER_SAMPLED_READ_BIT, "VK_ACCESS_2_SHADER_SAMPLED_READ_BIT");
		append(VK_ACCESS_2_SHADER_STORAGE_READ_BIT, "VK_ACCESS_2_SHADER_STORAGE_READ_BIT");
		append(VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT, "VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT");
		append(VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR, "VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR");
		append(VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR, "VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR");
		append(VK_ACCESS_2_SAMPLER_HEAP_READ_BIT_EXT, "VK_ACCESS_2_SAMPLER_HEAP_READ_BIT_EXT");
		append(VK_ACCESS_2_RESOURCE_HEAP_READ_BIT_EXT, "VK_ACCESS_2_RESOURCE_HEAP_READ_BIT_EXT");
		append(VK_ACCESS_2_VIDEO_ENCODE_READ_BIT_KHR, "VK_ACCESS_2_VIDEO_ENCODE_READ_BIT_KHR");
		append(VK_ACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHR, "VK_ACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHR");
		append(VK_ACCESS_2_SHADER_TILE_ATTACHMENT_READ_BIT_QCOM, "VK_ACCESS_2_SHADER_TILE_ATTACHMENT_READ_BIT_QCOM");
		append(VK_ACCESS_2_SHADER_TILE_ATTACHMENT_WRITE_BIT_QCOM, "VK_ACCESS_2_SHADER_TILE_ATTACHMENT_WRITE_BIT_QCOM");
		append(VK_ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, "VK_ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT");
		append(VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT, "VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT");
		append(VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, "VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT");
		append(VK_ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT, "VK_ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT");
		append(VK_ACCESS_2_COMMAND_PREPROCESS_READ_BIT_EXT, "VK_ACCESS_2_COMMAND_PREPROCESS_READ_BIT_EXT");
		append(VK_ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_EXT, "VK_ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_EXT");
		append(VK_ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR, "VK_ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR");
		append(VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR, "VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR");
		append(VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, "VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR");
		append(VK_ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT, "VK_ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT");
		append(VK_ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT, "VK_ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT");
		append(VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT, "VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT");
		append(VK_ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI, "VK_ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI");
		append(VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR, "VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR");
		append(VK_ACCESS_2_MICROMAP_READ_BIT_EXT, "VK_ACCESS_2_MICROMAP_READ_BIT_EXT");
		append(VK_ACCESS_2_MICROMAP_WRITE_BIT_EXT, "VK_ACCESS_2_MICROMAP_WRITE_BIT_EXT");
		append(VK_ACCESS_2_OPTICAL_FLOW_READ_BIT_NV, "VK_ACCESS_2_OPTICAL_FLOW_READ_BIT_NV");
		append(VK_ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV, "VK_ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV");
		append(VK_ACCESS_2_DATA_GRAPH_READ_BIT_ARM, "VK_ACCESS_2_DATA_GRAPH_READ_BIT_ARM");
		append(VK_ACCESS_2_DATA_GRAPH_WRITE_BIT_ARM, "VK_ACCESS_2_DATA_GRAPH_WRITE_BIT_ARM");
		append(VK_ACCESS_2_MEMORY_DECOMPRESSION_READ_BIT_EXT, "VK_ACCESS_2_MEMORY_DECOMPRESSION_READ_BIT_EXT");
		append(VK_ACCESS_2_MEMORY_DECOMPRESSION_WRITE_BIT_EXT, "VK_ACCESS_2_MEMORY_DECOMPRESSION_WRITE_BIT_EXT");

		VkAccessFlags2 unknownFlags = vkAccessFlags2 & ~knownFlags;
		if (unknownFlags != 0)
		{
			if (!first)
				ss << " | ";
			ss << "UNKNOWN_ACCESS_2_BITS(0x" << std::hex << static_cast<uint64_t>(unknownFlags) << std::dec << ")";
		}

		return ss.str();
	}
}