#include "vulkanBufferUsageFlagsToString.h"
#include <sstream>



namespace emberVulkanUtility
{
	std::string ToString_VkBufferUsageFlags(VkBufferUsageFlags vkBufferUsageFlags)
	{
		if (vkBufferUsageFlags == 0)
			return "none";
		if (vkBufferUsageFlags == VK_BUFFER_USAGE_FLAG_BITS_MAX_ENUM)
			return "VK_BUFFER_USAGE_FLAG_BITS_MAX_ENUM";

		std::ostringstream ss;
		bool first = true;
		VkBufferUsageFlags knownFlags = 0;
		auto append = [&](VkBufferUsageFlagBits bit, const char* name)
		{
			knownFlags |= bit;
			if (vkBufferUsageFlags & bit)
			{
				if (!first)
					ss << " | ";
				first = false;
				ss << name;
			}
		};

		append(VK_BUFFER_USAGE_TRANSFER_SRC_BIT, "VK_BUFFER_USAGE_TRANSFER_SRC_BIT");
		append(VK_BUFFER_USAGE_TRANSFER_DST_BIT, "VK_BUFFER_USAGE_TRANSFER_DST_BIT");
		append(VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT, "VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT");
		append(VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT, "VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT");
		append(VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, "VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT");
		append(VK_BUFFER_USAGE_STORAGE_BUFFER_BIT, "VK_BUFFER_USAGE_STORAGE_BUFFER_BIT");
		append(VK_BUFFER_USAGE_INDEX_BUFFER_BIT, "VK_BUFFER_USAGE_INDEX_BUFFER_BIT");
		append(VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, "VK_BUFFER_USAGE_VERTEX_BUFFER_BIT");
		append(VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT, "VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT");
		append(VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT, "VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT");
		append(VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR, "VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR");
		append(VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR, "VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR");
		append(VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT");
		append(VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT");
		append(VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT, "VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT");
		#ifdef VK_ENABLE_BETA_EXTENSIONS
		append(VK_BUFFER_USAGE_EXECUTION_GRAPH_SCRATCH_BIT_AMDX, "VK_BUFFER_USAGE_EXECUTION_GRAPH_SCRATCH_BIT_AMDX");
		#endif
		append(VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR, "VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR");
		append(VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR, "VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR");
		append(VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR, "VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR");
		append(VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR, "VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR");
		append(VK_BUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHR, "VK_BUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHR");
		append(VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT");
		append(VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT");
		append(VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT");
		append(VK_BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT, "VK_BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT");
		append(VK_BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT, "VK_BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT");

		VkBufferUsageFlags unknownFlags = vkBufferUsageFlags & ~knownFlags;
		if (unknownFlags != 0)
		{
			if (!first)
				ss << " | ";
			ss << "UNKNOWN_BUFFER_USAGE_BITS(0x" << std::hex << static_cast<uint32_t>(unknownFlags) << std::dec << ")";
		}

		return ss.str();
	}
}