#include "vulkanColorSpaceToString.h"



namespace emberVulkanUtility
{
	std::string ToString(VkColorSpaceKHR vkColorSpace)
	{
		switch (vkColorSpace)
		{
			case VK_COLOR_SPACE_SRGB_NONLINEAR_KHR:
				return "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR";
			case VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT:
				return "VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT";
			case VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT:
				return "VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT";
			case VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT:
				return "VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT";
			case VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT:
				return "VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT";
			case VK_COLOR_SPACE_BT709_LINEAR_EXT:
				return "VK_COLOR_SPACE_BT709_LINEAR_EXT";
			case VK_COLOR_SPACE_BT709_NONLINEAR_EXT:
				return "VK_COLOR_SPACE_BT709_NONLINEAR_EXT";
			case VK_COLOR_SPACE_BT2020_LINEAR_EXT:
				return "VK_COLOR_SPACE_BT2020_LINEAR_EXT";
			case VK_COLOR_SPACE_HDR10_ST2084_EXT:
				return "VK_COLOR_SPACE_HDR10_ST2084_EXT";
			case VK_COLOR_SPACE_DOLBYVISION_EXT:
				return "VK_COLOR_SPACE_DOLBYVISION_EXT";
			case VK_COLOR_SPACE_HDR10_HLG_EXT:
				return "VK_COLOR_SPACE_HDR10_HLG_EXT";
			case VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT:
				return "VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT";
			case VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT:
				return "VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT";
			case VK_COLOR_SPACE_PASS_THROUGH_EXT:
				return "VK_COLOR_SPACE_PASS_THROUGH_EXT";
			case VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT:
				return "VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT";
			case VK_COLOR_SPACE_DISPLAY_NATIVE_AMD:
				return "VK_COLOR_SPACE_DISPLAY_NATIVE_AMD";
			case VK_COLOR_SPACE_MAX_ENUM_KHR:
				return "VK_COLOR_SPACE_MAX_ENUM_KHR";
			default:
				return "unknown";
		}
	}
}